// Generated by CoffeeScript 1.6.2
(function() {
  var fs, stitch;

  fs = require('fs');

  stitch = require('stitch');

  stitch.createPackage({
    paths: ['dist']
  }).compile(function(err, jsCode) {
    if (err) {
      throw err;
    }
    return fs.writeFile('dist/web/u-stitched.js', jsCode, function(err) {
      if (err) {
        throw err;
      }
    });
  });

}).call(this);
